16_TranThanhHau_Buoi2_BTVN/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _16_TranThanhHau_Buoi2_BTVN.Models
{
    public class User
    {
        public string login { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    }
}

16_TranThanhHau_Buoi2_BTVN/Controllers/Bai11_HomeDNDKController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _16_TranThanhHau_Buoi2_BTVN.Controllers
{
    public class Bai11_HomeDNDKController : Controller
    {
        //
        // GET: /Bai11_HomeDNDK/

        public ActionResult HomeDNDK()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("DangNhap", "Bai11_HomePage");
            }
            return View();
        }

    }
}

16_TranThanhHau_Buoi2_BTVN/Controllers/Bai11_HomePageController.cs
using _16_TranThanhHau_Buoi2_BTVN.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _16_TranThanhHau_Buoi2_BTVN.Controllers
{
    public class Bai11_HomePageController : Controller
    {
        //
        // GET: /Bai11_HomePage/

        public ActionResult Home()
        {
            return View();
        }
        public ActionResult SanPham_Bai11()
        {
            return View();
        }
        public ActionResult Lienhe()
        {
            return View();
        }
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap([Bind(Include = "UserName, Password,Email")]User user)
        {
            if ("huit".Equals(user.UserName) && "123456".Equals(user.Password) && "tranhau2607@gmail.com".Equals(user.Email))
            {
                Session["user"] = new User() { login = user.UserName, UserName = "Trần Thanh Hậu" };
            }
            return RedirectToAction("HomeDNDK", "Bai11_HomeDNDK");
        }

        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(string UserName, string Name, string Email, string Password, string NamSinh, string RetypePassword, string GioiTinh)
        {
            if (UserName.Length >= 2 && Name.Length >= 3 && Password.Length >= 6 && RetypePassword == Password)
                return RedirectToAction("DangNhap", "Bai11_HomePage");
            return View();
        }

    }
}

16_TranThanhHau_Buoi2_BTVN/Controllers/Bai_78910Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _16_TranThanhHau_Buoi2_BTVN.Controllers
{
    public class Bai_78910Controller : Controller
    {
        //
        // GET: /Bai_78910/

        public ActionResult trangchu()
        {
            return View();
        }
        public ActionResult Bai7()
        {
            return View();
        }
        public ActionResult Bai8()
        {
            return View();
        }
        public ActionResult Bai9()
        {
            return View();
        }
        public ActionResult Bai10()
        {
            return View();
        }

    }
}

16_TranThanhHau_Buoi2_BTVN/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _16_TranThanhHau_Buoi2_BTVN.Controllers
{
    public class HomePageController : Controller
    {
        //
        // GET: /HomePage/

        public ActionResult Index()
        {
            return View();
        }

    }
}

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomeDNDK/HomeDNDK.cshtml
@{
    ViewBag.Title = "HomeDNDK";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}

@model _16_TranThanhHau_Buoi2_BTVN.Models.User
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    @{
        var user = Session["user"] as _16_TranThanhHau_Buoi2_BTVN.Models.User;
    }
    <h2>Welcome @user.UserName</h2>
    <a href="/Bai11_HomePage/DangNhap">Đăng Xuất</a>
</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomePage/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}
@model _16_TranThanhHau_Buoi2_BTVN.Models.User
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DangKy</title>
    <link href="@Url.Content("~/Content/style_Bai11.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <form action="/Bai11_HomePage/DangKy" method="post">
        <div class="dangky">
            <h1>Đăng ký thành viên</h1>
            <div class="hoten">
                <input type="text" placeholder="Họ" id="username" name="username">
                <input type="text" placeholder="Tên" id="name" name="name">
            </div>
            <div class="chung">
                <input type="text" placeholder="Email" id="email" name="email">
            </div>
            <div class="chung">
                <input type="text" placeholder="Mật khẩu" id="password" name="password">
            </div>
            <div class="chung">
                <input type="text" placeholder="Nhập Lại Mật khẩu" id="retypepassword" name="retypepassword">
            </div>
            <div class="chung">
                <label for="">Ngày sinh</label>
                <input type="date">
            </div>
            <div class="gioitinh">
                <input name="gioitinh" type="radio" value="Nam">Nam
                <input name="gioitinh" type="radio" value="Nữ">Nữ
            </div>
            <div>
                <button type="submit">Đăng Ký</button>
            </div>
        </div>
    </form>

</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomePage/DangNhap.cshtml
@{
    ViewBag.Title = "DangNhap";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}
@model _16_TranThanhHau_Buoi2_BTVN.Models.User
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DangNhap</title>
    <link href="@Url.Content("~/Content/style_Bai11.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <form action="/Bai11_HomePage/DangNhap" method="post">
        <div class="dangnhap">
            <h1>Đăng Nhập</h1>
            <div class="container">
                <label for="email"><b>Email</b></label>
                <input type="email" placeholder="Email" id="email" name="email" />

                <label for="username"><b>Họ và tên</b></label>
                <input type="text" placeholder="UserName" id="username" name="username" />

                <label for="password"><b>Mật Khẩu</b></label>
                <input type="password" placeholder="Password" id="password" name="password" />
                <label>
                    <input type="checkbox" checked="checked" name="remember"> Lưu thông tin
                </label>
                <div>
                    <button type="submit">Đăng Nhập</button>
                </div>
            </div>
            <div class="containe">
                <span class="psw"><a href="/Bai11_DangKy/DangKy">Đăng Ký</a></span>
            </div>
        </div>
    </form>

</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomePage/Home.cshtml
@{
    ViewBag.Title = "Home";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}

<h1>Trang Chủ</h1>

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomePage/Lienhe.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}
@model _16_TranThanhHau_Buoi2_BTVN.Models.User
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Liên Hệ</title>
    <link href="@Url.Content("~/Content/style_Bai11.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <h1>Thông tin liên hệ</h1>
    <div class="lienhe">
        <p>Quý khách có nhu cầu vui lòng liên hệ:</p>
        <h2>Cửa hàng Bá Minh</h2>
        <p>Địa chỉ: 140 Lê Trọng Tấn, phường Tây Thạch, Quận Tân Phú</p>
        <p>Điện thoại: 0935992567</p>
    </div>
</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai11_HomePage/SanPham_Bai11.cshtml
@{
    ViewBag.Title = "SanPham_Bai11";
    Layout = "~/Views/Shared/_Layout_Bai11.cshtml";
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--butrap-->
    <!-- ICON-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="@Url.Content("~/Content/style_Bai11.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <section class="product-small" id="product-small">
        <div class="product-container-small">
            <div class="box">
                <a href=""><img src="/Content/images/bai11_h1.jpg" alt=""></a>
                <h3>Sản phẩm 1</h3>
                <div class="">
                    <p>Lựa chọn hàng đầu, thiết kế đẹp, chất lượng tốt, lượng người mua nhiều, an toàn, phù hợp với nhu cầu người tiêu dùng</p>
                </div>
                <div class="content">
                    <a href="">Chọn Mua</a>
                </div>
            </div>
            <div class="box">
                <a href=""><img src="/Content/images/bai11_h2.jpg" alt=""></a>

                <h3>Sản phẩm 2</h3>
                <div class="">
                    <p>Lựa chọn hàng đầu, thiết kế đẹp, chất lượng tốt, lượng người mua nhiều, an toàn, phù hợp với nhu cầu người tiêu dùng</p>
                </div>
                <div class="content">
                    <a href="">Chọn Mua</a>
                </div>
            </div>
            <div class="box">
                <a href=""><img src="/Content/images/bai11_h3.jpg" alt=""></a>

                <h3>Sản phẩm 3</h3>
                <div class="">
                    <p>Lựa chọn hàng đầu, thiết kế đẹp, chất lượng tốt, lượng người mua nhiều, an toàn, phù hợp với nhu cầu người tiêu dùng</p>
                </div>
                <div class="content">
                    <a href="">Chọn Mua</a>
                </div>
            </div>
            <div class="box">
                <a href=""><img src="/Content/images/bai11_h4.jpg" alt=""></a>

                <h3>Sản phẩm 4</h3>
                <div class="">
                    <p>Lựa chọn hàng đầu, thiết kế đẹp, chất lượng tốt, lượng người mua nhiều, an toàn, phù hợp với nhu cầu người tiêu dùng</p>
                </div>
                <div class="content">
                    <a href="">Chọn Mua</a>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai_78910/Bai10.cshtml
@{
    ViewBag.Title = "Bai10";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="bai10_contact">
        <h1>Thông tin liên hệ</h1>
        <p>Vui lòng liên hệ đến:</p>
        <h1>Trần Thanh Hậu</h1>
        <p>MSSV: 2001211917</p>
        <p>Địa chỉ: 140 Lê Trọng Tấn, phường Tây Thạch, Quận Tân Phú</p>
        <p>Email: tranhau2607@gmail.com</p>
    </div>
</body>

</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai_78910/Bai7.cshtml
@{
    ViewBag.Title = "Bai7";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <section>
        <div class="tieude">
            <h1>portfloio</h1>
            <p>Lorem ipsum dolor sit amet consectetur</p>
        </div>
        <div class="noidung">
            <div class="h1">
                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i1.png" alt="Alternate Text" /></a>
                    <h3>Threads </h3>
                    <p>Illustration</p>
                </div>

                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i2.png" alt="Alternate Text" /></a>
                    <h3>Explore</h3>
                    <p>Graphic Deign</p>
                </div>
                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i3.png" alt="Alternate Text" /></a>
                    <h3>Finish</h3>
                    <p>Identty</p>
                </div>
            </div>
            <div class="h2">
                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i4.png" alt="Alternate Text" /></a>
                    <h3>Lines</h3>
                    <p>Branding</p>
                </div>
                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i5.png" alt="Alternate Text" /></a>
                    <h3>Southwest</h3>
                    <p>Website Design</p>
                </div>
                <div class="nn">
                    <a href="/Bai_78910/Bai8"><img src="/Content/images/i6.png" alt="Alternate Text" /></a>
                    <h3>Window</h3>
                    <p>Photography</p>
                </div>
            </div>
        </div>

    </section>
</body>

</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai_78910/Bai8.cshtml
@{
    ViewBag.Title = "Bai8";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="about">
        <div class="anh">
            <img src="/Content/images/i1.png" alt="Alternate Text" />
        </div>
        <div class="gioithieu">
            <h1>Threads</h1>
            <p>Web programming helps us learn the necessary information, build our own website, skills to work, improve ourselves, try to complete the exercises, practice every day.</p>
        </div>
    </div>

</body>

</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai_78910/Bai9.cshtml
@{
    ViewBag.Title = "Bai9";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <section>
        <div class="tieude">
            <h1>Team</h1>
        </div>
        <div class="noidung">
            <div class="h1">
                <div class="nn">
                    <img src="/Content/images/bai9_h1.jpg" alt="Alternate Text" />
                    <h3>Trần Thanh Hậu </h3>
                    <p>2001211917</p>
                </div>

                <div class="nn">
                    <img src="/Content/images/bai9_h2.jpg" alt="Alternate Text" />
                    <h3>Nguyễn Tấn Đạt</h3>
                    <p>2001210166</p>
                </div>
                <div class="nn">
                    <img src="/Content/images/bai9_h3.jpg" alt="Alternate Text" />
                    <h3>Trần Khánh Nam</h3>
                    <p>2001210288</p>
                </div>
            </div>
        </div>
    </section>
</body>

</html>

16_TranThanhHau_Buoi2_BTVN/Views/Bai_78910/trangchu.cshtml
@{
    ViewBag.Title = "trangchu";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2 class="trangchu_bai78910">Trang Chủ</h2>

16_TranThanhHau_Buoi2_BTVN/Views/HomePage/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutHomePage.cshtml";
}

<h2>Trang chủ các bài tập</h2>

16_TranThanhHau_Buoi2_BTVN/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Shared/_LayoutHomePage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="@Url.Content("~/Content/style_layouthomepage.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="tieudepage">
        <h2>Lập trình Web</h2>
    </div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/HomePage/Index" style="font-size: 35px;padding-right: 30px;color: var(--main-color);">LAPTRINHWEB</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/HomePage/Index">Trang Chủ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Giới thiệu</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Thông báo
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="#">Đăng Nhập</a></li>
                            <li><a class="dropdown-item" href="#">Đăng Ký</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Xem thêm</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <section>
        <div class="containe">
            <div class="search_tt">
                <h1>Tổng các buổi học</h1>
                <h1>DAY 2</h1>
                <div class="menu">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Bài 7", "Bai7", "Bai_78910")</li>
                        <li>@Html.ActionLink("Bài 8", "Bai8", "Bai_78910")</li>
                        <li>@Html.ActionLink("Bài 9", "Bai9", "Bai_78910")</li>
                        <li>@Html.ActionLink("Bài 10", "Bai10", "Bai_78910")</li>
                        <li>@Html.ActionLink("Bài 11", "Home", "Bai11_HomePage")</li>
                    </ul>
                    @*<ul>
                        <li><a href="/Bai_78910/Bai7">Bài 7</a></li>
                        <li><a href="/Bai_78910/Bai8">Bài 8</a></li>
                        <li><a href="/Bai_78910/Bai9">Bài 9</a></li>
                        <li><a href="/Bai_78910/Bai10">Bài 10</a></li>
                        <li><a href="/Bai11_HomePage/Home">Bài 11</a></li>
                    </ul>*@
                </div>
            </div>
            <div class="content">
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>

    </section>


    <div class="footer">
        <p>16 - Trần Thanh Hậu - 2001211917</p>
        <p>Độc quyền -2023-TTH</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Shared/_LayoutPage.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/style.css")" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
        <div class="menu">
            <div class="logo">
                <a href="">Start Bootstrap</a>
            </div>
            <div class="congcu">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Services", "trangchu", "Bai_78910")</li>
                    <li>@Html.ActionLink("Fortfolio", "Bai7", "Bai_78910")</li>
                    <li>@Html.ActionLink("About", "Bai8", "Bai_78910")</li>
                    <li>@Html.ActionLink("Team", "Bai9", "Bai_78910")</li>
                    <li>@Html.ActionLink("Contact", "Bai10", "Bai_78910")</li>
                    <li>@Html.ActionLink("Quay lại HomePage", "Index", "HomePage")</li>
                </ul>
            </div>
            @*<div class="congcu">
                    <ul>
                        <li><a href="/Bai_78910/trangchu">services</a></li>
                        <li><a href="/Bai_78910/Bai7">fortfolio</a></li>
                        <li><a href="/Bai_78910/Bai8">about</a></li>
                        <li><a href="/Bai_78910/Bai9">team</a></li>
                        <li><a href="#">contact</a></li>
                    </ul>
                </div>*@
        </div>
        <div class="container">
            @RenderBody()
        </div>
    </header>
    
    <footer>
        <div class="f1">
            <p>Copyright Your Website 2019</p>
        </div>
        <div class="icon_footer">
            <i class="fa fa-brands fa-twitter"></i>
            <i class="fa fa-brands fa-facebook"></i>
            <i class="fa fa-solid fa-location-dot"></i>
        </div>
        <div class="f2">
            <p>Privacy Policy Terms of Use</p>
        </div>
    </footer>
</body>
</html>

16_TranThanhHau_Buoi2_BTVN/Views/Shared/_Layout_Bai11.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link href="@Url.Content("~/Content/style_Bai11.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="tieudepage">
        <img src="/Content/images/bai11_tieude.png" alt="Alternate Text" />
    </div>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/Bai11_HomePage/Home">Trang Chủ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Bai11_HomePage/SanPham_Bai11">Sản phẩm</a>

                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Bai11_HomePage/DangNhap">Đăng nhập</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Bai11_HomePage/DangKy">Đăng ký</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Bai11_HomePage/lienhe">Liên hệ</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/HomePage/Index" style="color:green">Quay lại HomePage</a>
                    </li>
                    
                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <section>
        <div class="containe">
            <div class="search_tt">
                <h1>danh mục sản phẩm</h1>
                <div class="menu">
                    <ul>
                        <li><a href="">Mái xếp</a></li>
                        <li><a href="">Mái che</a></li>
                        <li><a href="">Mái vòm</a></li>
                        <li><a href="">Mái hiên di động</a></li>
                    </ul>
                </div>
                <h1>Hỗ trợ trực tuyến</h1>
                <h1>Thống kê truy cập</h1>
                <div class="menu">

                </div>
            </div>
            <div class="content">
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>

    </section>

    <div class="footer">
        <p>16 - Trần Thanh Hậu - 2001211917</p>
        <p>Độc quyền -2023-TTH</p>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>